services:
  # Backend Service
  - type: web
    name: fake-news-detection-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DATABASE
        value: fake_news_detection

  # Frontend Service
  - type: web
    name: fake-news-detection-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://fake-news-detection-s4xf.onrender.com 